# Generated by Django 2.2.14 on 2023-03-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='timesAddedToCart',
            field=models.IntegerField(default=0),
        ),
    ]
